### ISSUE TITLE
Add a location

### ISSUE THREAD

**Issue by kcallaghan1** [kcallaghan1/traveltracker#4]
In order to remember where I have been and recommend it to others
As a tourist
I need to add a location

**Comment by hoshamania** [comment]
When a user opens their travel log, they are able to add a location to their log, from a list of predetermined locations. They can also add a location from their favorites/a personal location.

**Comment by hoshamania** [comment]
When a user opens their travel log, they are able to add a location to their log, from a list of predetermined locations. They can also add a location from their favorites/a personal location.
